Change fzf preview window size

diff --git a/dot_config/shell/executable_functions b/dot_config/shell/executable_functions
--- a/dot_config/shell/executable_functions
+++ b/dot_config/shell/executable_functions
@@ -1,66 +1,61 @@
 #!/bin/sh
 
-
 # archive extraction
-ex ()
-{
-  if [ -f "$1" ] ; then
-    case "$1" in
-      *.tar.bz2)   tar xjf "$1"   ;;
-      *.tar.gz)    tar xzf "$1"   ;;
-      *.bz2)       bunzip2 "$1"   ;;
-      *.rar)       unrar x "$1"   ;;
-      *.gz)        gunzip "$1"    ;;
-      *.tar)       tar xf "$1"    ;;
-      *.tbz2)      tar xjf "$1"   ;;
-      *.tgz)       tar xzf "$1"   ;;
-      *.zip)       unzip "$1"     ;;
-      *.Z)         uncompress "$1";;
-      *.7z)        7z x "$1"      ;;
-      *.iso)       7z x "$1"      ;;
-      *.deb)       ar x "$1"      ;;
-      *.tar.xz)    tar xf "$1"    ;;
-      *.tar.zst)   unzstd "$1"    ;;
-      *)           echo "'$1' cannot be extracted via ex()" ;;
-    esac
-  else
-    echo "'$1' is not a valid file"
-  fi
+ex() {
+	if [ -f "$1" ]; then
+		case "$1" in
+		*.tar.bz2) tar xjf "$1" ;;
+		*.tar.gz) tar xzf "$1" ;;
+		*.bz2) bunzip2 "$1" ;;
+		*.rar) unrar x "$1" ;;
+		*.gz) gunzip "$1" ;;
+		*.tar) tar xf "$1" ;;
+		*.tbz2) tar xjf "$1" ;;
+		*.tgz) tar xzf "$1" ;;
+		*.zip) unzip "$1" ;;
+		*.Z) uncompress "$1" ;;
+		*.7z) 7z x "$1" ;;
+		*.iso) 7z x "$1" ;;
+		*.deb) ar x "$1" ;;
+		*.tar.xz) tar xf "$1" ;;
+		*.tar.zst) unzstd "$1" ;;
+		*) echo "'$1' cannot be extracted via ex()" ;;
+		esac
+	else
+		echo "'$1' is not a valid file"
+	fi
 }
 
-cdd () {
-    mkdir "$1"
-    cd "$1" || exit 1
+cdd() {
+	mkdir "$1"
+	cd "$1" || exit 1
 }
-
 
 # list git repositories and cd
-gf () {
-    cd "$(ghq list -p | fzf -1 --delimiter='/' --with-nth=5.. --preview="onefetch --no-bold --no-palette --show-logo never {}")"
+gf() {
+	cd "$(ghq list -p | fzf -1 --delimiter='/' --with-nth=5.. --preview="onefetch --no-bold --no-palette --show-logo never {}")"
 }
 
-qira (){
-    docker run --rm -v "$PWD":/mnt -p 3002:3002 -p 4000:4000 -ti qira bash
+qira() {
+	docker run --rm -v "$PWD":/mnt -p 3002:3002 -p 4000:4000 -ti qira bash
 }
 
-
-lr () {
-    fullpath="$(readlink -f "$1")"
-    command="entr -ccr"
-    [ -x "$fullpath" ] || command="$command cat"
-    /usr/bin/ls "$fullpath" | eval "$command $fullpath"
+lr() {
+	fullpath="$(readlink -f "$1")"
+	command="entr -ccr"
+	[ -x "$fullpath" ] || command="$command cat"
+	/usr/bin/ls "$fullpath" | eval "$command $fullpath"
 }
-
 
 # i use arch btw
 pf() {
-    pacman -Slq | fzf --multi --preview 'cat <(pacman -Si {1}) <(pacman -Fl {1} | awk "{print \$2}")' | xargs -ro sudo pacman -S
+	pacman -Slq | fzf --multi --preview-window '55%,wrap' --preview 'cat <(pacman -Si {1}) <(pacman -Fl {1} | awk "{print \$2}")' | xargs -ro sudo pacman -S
 }
 
 ppf() {
-    paru -Slq | fzf --multi --preview 'cat <(paru -Si {1}) <(paru -Fl {1} | awk "{print \$2}")' | xargs -ro paru -S
+	paru -Slq | fzf --multi --preview-window '55%,wrap' --preview 'cat <(paru -Si {1}) <(paru -Fl {1} | awk "{print \$2}")' | xargs -ro paru -S
 }
 
 pd() {
-    pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns
+	pacman -Qq | fzf --multi --preview-window '55%,wrap' --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns
 }
